### ISSUE TITLE
Getting an error on when using the deploy action

### ISSUE THREAD

**Issue by grascioni** [evalytica/dotnet-lambda-actions#1]
```
##[warning]Failed to download action 'https://api.github.com/repos/actions/aws/tarball/master'. Error Response status code does not indicate success: 404 (Not Found).
##[warning]Back off 21.007 seconds before retry.
##[warning]Failed to download action 'https://api.github.com/repos/actions/aws/tarball/master'. Error Response status code does not indicate success: 404 (Not Found).
##[warning]Back off 13.269 seconds before retry.
##[error]Response status code does not indicate success: 404 (Not Found).
```

**Comment by grascioni** [comment]
Fixed by simply removing the following step:
```
- name: Use AWS CLI
  uses: actions/aws/cli@master
```

**Comment by aharden** [comment]
@grascioni Thanks for the report! The AWS CLI actions has been deprecated, and the AWS CLI is in at least some of the GitHub-hosted runners, which is what removing the step fell back to.  I'll update the action to reflect this soon.

https://github.com/aws/aws-cli/issues/4835

Update: In updating this I found that our Dockerfile performs a `pip3 install awscli`, which provides AWS CLI coverage (and upgrade to latest release version).  I'm going to leave this in for now, since some may use this on non-GitHub-hosted Actions runners.
